
#
file:
  local:
    savePah: /home/java/file/
    url: http://demo.com
# datasoure
db:
  datasource:
    hostIP: mysql
    userName: root
    password: root
    savePath: /home/java/db
spring:
  datasource:
      url: jdbc:mysql://mysql:3306/shop?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        minimum-idle: 1
        maximum-pool-size: 20
        pool-name: bosPoolName
        max-lifetime: 180000

##mybaits-plus配置，
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: .api.model.entity
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true



